apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsql-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsql-proxy
  template:
    metadata:
      labels:
        app: cloudsql-proxy
        unit: mycloudsql
    spec:
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
        command: ["/cloudsql-proxy",
            "-instances=vaporgaming-umd:us-east5:vaporgaming-umd=tcp:0.0.0.0:3306",
            "-credential_file=/VaporGaming-UMD/vaporgaming-umd-043ee9946f6a.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /VaporGaming-UMD/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir: