version: "2"
services:
  webserver:
    image: webserver
    ports:
      - "80:80"
    #volumes:
    #  - ./app:/var/www/html
    environment:
      MYSQL_DB_CONNECTION: 127.0.0.1
      MYSQL_DB_NAME: AccountInformation
      MYSQL_USER: aaronmyrick
      MYSQL_PASSWORD: UMD-3232733174
      SITE_URL: http://vaporgaming
    networks:
      - test

networks:
  test:
    external: true