version: "2"
services:
  webserver:
    image: webserver
    ports:
      - "8080:80"
    #volumes:
    #  - ./app:/var/www/html
    environment:
      MYSQL_DB_CONNECTION: 10.11.12.6
      MYSQL_DB_NAME: AccountInformation
      MYSQL_USER: aaronmyrick
      MYSQL_PASSWORD: UMD-123

networks:
  test:
    external: true